telegram:
  webhookUrl: "https://hook.us1.make.com/xxxxx"
  chatId: "-1001234567890"

paths:
  dataDirectory: "C:/Users/manut/OneDrive/Documentos/RegistroMedicoApp/Patients"

app:
  notificationHour: 21
  notificationMinute: 0